## TASK 2

In [22]:
source("./Imports.R")

## Description
Select 4 columns: Year, Month, PostsNumber, MaxScore from Posts table passed as parameter to function  
Year: Extracted year from CreationData  
Month: Extracted month from CreationData  
PostsNumber: Post number  
MaxScore: Max score  
Takes only Posts where PostIdType is 1 or 2  
Groups it by Year then by Month  
Returns only groups with more that 1000 posts  

### Effectively returns months and years when there was at least 1001 posts of category 1 or 2

In [23]:
sql_2 <- function(Posts){
    sqldf("SELECT STRFTIME('%Y', CreationDate) AS Year, STRFTIME('%m', CreationDate) AS Month,
        COUNT(*) AS PostsNumber, MAX(Score) AS MaxScore
        FROM Posts
        WHERE PostTypeId IN (1, 2)
        GROUP BY Year, Month
        HAVING PostsNumber > 1000")
}

In [24]:
base_2 <- function(Posts){
    Posts$Year <- format(as.POSIXct(Posts$CreationDate), "%Y")
    Posts$Month <- format(as.POSIXct(Posts$CreationDate), "%m")
    posts_with_filtered_id <- subset(Posts, (PostTypeId == 1 | PostTypeId == 2))
    posts_agg_posts_number <- aggregate(
        cbind(PostsNumber = Id) ~ Year + Month,
        data = posts_with_filtered_id,
        FUN = length)
    posts_agg_posts_max <- aggregate(
        cbind(MaxScore = Score) ~ Year + Month,
        data = posts_with_filtered_id,
        FUN = max)
    posts_agg <- merge(posts_agg_posts_number,posts_agg_posts_max,by=c("Year","Month"))
    posts_agg <- posts_agg[posts_agg$PostsNumber > 1000,]
    return(posts_agg)
}

In [25]:
dplyr_2 <- function(Posts){
    as.data.frame(
        Posts %>%
        mutate(Year = format(as.POSIXct(CreationDate), "%Y"), 
            Month = format(as.POSIXct(CreationDate), "%m")) %>%
        filter((PostTypeId == 1 | PostTypeId == 2)) %>%
        group_by(Year, Month) %>%
        summarise(PostsNumber = n(), MaxScore = max(Score),.groups="drop") %>%
        filter(PostsNumber > 1000) 
    )
}

In [26]:
table_2 <- function(Posts){
    setDT(Posts)
    Posts[,Year := format(as.POSIXct(CreationDate), "%Y")]
    Posts[,Month := format(as.POSIXct(CreationDate), "%m")]
    posts_with_filtered_id <- Posts[(PostTypeId == 1 | PostTypeId == 2)]
    posts_agg <- posts_with_filtered_id[,
                            .(PostsNumber = .N, MaxScore = max(Score)),
                            by = .(Year, Month)]
    posts_agg_filtered <- posts_agg[PostsNumber > 1000,]
    return(as.data.frame(posts_agg_filtered))
}

In [27]:
comp(
    sql_2(Posts),
    base_2(Posts),
    dplyr_2(Posts),
    table_2(Posts)
)

[1] "COMPARING GIVEN OUTPUTS TO SQL ONE: "
[1] "BASE: TRUE"
[1] "DPLYR: TRUE"
[1] "TABLE: TRUE"

In [28]:
table_2(Posts)

   Year Month PostsNumber MaxScore
1  2014 05    1012        133
2  2014 06    1053         74
3  2014 07    1068         80
4  2014 08    1030         58
5  2015 03    1195         73
6  2015 04    1191         71
7  2015 05    1233         90
8  2015 06    1511        165
9  2015 07    1191         81
10 2015 08    1269        126
11 2015 09    1117        132
12 2015 12    1056        149
13 2016 01    1097        172
14 2016 03    1079         69
15 2016 04    1189        217
16 2016 05    1436        240
17 2016 06    1756        154
18 2016 07    1777         95
19 2016 08    1661        145
20 2016 09    1576        132
21 2016 10    1424        126
22 2016 11    1145        108
23 2016 12    1314         88
24 2017 01    1426        156
25 2017 02    1292         95
26 2017 03    1437        107
27 2017 04    1206        110
28 2017 05    1288         89
29 2017 06    1432        113
30 2017 07    1522        546
31 2017 08    1575        265
32 2017 09    1333        179
33 2017 10    1236        204
34 2017 11    1059        130
35 2017 12    1158        147
36 2018 01    1090        135
37 2018 02    1076        126
38 2018 03    1245        158
39 2018 04    1351        132
40 2018 05    1419        119
41 2018 06    1223        245
42 2018 07    1526        156
43 2018 08    1439         94
44 2018 09    1118        128
45 2018 10    1276        154
46 2018 11    1082        117
47 2018 12    1212        258
48 2019 01    1530        154
49 2019 02    1248        226
50 2019 03    1370        136
51 2019 04    1289        112
52 2019 05    1468        125
53 2019 06    1164        141
54 2019 07    1322        118
55 2019 08    1477        137
56 2019 09    1435        160
57 2019 10    1007         80
58 2019 12    1045        111
59 2020 01    1131        129
60 2020 02    1008        164